openapi: 3.0.1

info:
  title: Rarecips API
  description: API documentation for Rarecips
  version: v0

servers:
  - url: http://localhost:8443/api

paths:
  /recipes:
    get:
      summary: Get a list of recipes
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 0
          description: Page number for pagination (0-indexed)
        - in: query
          name: size
          schema:
            type: integer
            default: 3
          description: Number of recipes per page
        - in: query
          name: order
          schema:
            type: string
            enum: [lastmod]
            default: lastmod
      responses:
        '200':
          description: A list of recipes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe'
        '400':
          description: Invalid request parameters
        '500':
          description: Server error

  /recipes/{id}:
    get:
      summary: Get a recipe by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The recipe ID
      responses:
        '200':
          description: A single recipe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        '404':
          description: Recipe not found
        '500':
          description: Server error