package frontend.unit;

// Generated by Selenium IDE - Adapted for JUnit 5
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.time.Duration;

public class UIAuthTest extends BaseUnitTest {
  private JavascriptExecutor js;

  @BeforeEach
  public void setUpTest() {
    super.setUp();
    js = (JavascriptExecutor) driver;
  }

  @Test
  public void testLogin() {
    driver.get(baseUrl + "/login");
    driver.manage().window().setSize(new Dimension(1920, 1080));

    helper.pause(500);

    helper.waitAndSendKeys(By.id("login-username"), "testuser");
    helper.waitAndSendKeys(By.id("login-password"), "testpassword123_");

    js.executeScript("window.scrollTo(0,100)");

    helper.waitAndClick(By.id("loginBut"));

    js.executeScript("window.scrollTo(0,54)");

    helper.pause(1000);
  }

  @Test
  public void testSignup() {
    driver.get(baseUrl + "/signup");
    driver.manage().window().setSize(new Dimension(1920, 1080));

    helper.pause(500);

    helper.waitAndSendKeys(By.id("signup-username"), "testuser");
    helper.waitAndSendKeys(By.id("signup-email"), "testuser@example.com");
    helper.waitAndSendKeys(By.id("signup-password"), "testpassword123_");
    helper.waitAndSendKeys(By.id("signup-confirm-password"), "testpassword123_");

    helper.jsClickAfterVisible(By.cssSelector("input[type='checkbox']:nth-of-type(1) + span.checkbox-custom"));

    js.executeScript("window.scrollTo(0,0)");

    helper.waitAndClick(By.id("signupBut"));

    helper.pause(1000);
  }
}
