package frontend.unit;

// Generated by Selenium IDE - Adapted for JUnit 5
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

public class UIAuthTest extends BaseUnitTest {
  private JavascriptExecutor js;

  @BeforeEach
  public void setUpTest() {
    super.setUp();
    js = (JavascriptExecutor) driver;
  }

  @Test
  public void testLogin() {
    driver.get(baseUrl + "/login");
    driver.manage().window().setSize(new Dimension(1094, 944));

    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("testuser");

    js.executeScript("window.scrollTo(0,100)");

    driver.findElement(By.id("login-password")).sendKeys("testpassword123_");
    driver.findElement(By.id("loginBut")).click();

    js.executeScript("window.scrollTo(0,54)");
  }

  @Test
  public void testSignup() {
    driver.get(baseUrl + "/signup");
    driver.manage().window().setSize(new Dimension(1094, 944));

    driver.findElement(By.id("signup-username")).click();
    driver.findElement(By.id("signup-username")).sendKeys("testuser");
    driver.findElement(By.id("signup-email")).sendKeys("testuser@example.com");
    driver.findElement(By.id("signup-password")).sendKeys("testpassword123_");
    driver.findElement(By.id("signup-confirm-password")).sendKeys("testpassword123_");

    driver.findElement(By.cssSelector(".form-options:nth-child(6) .checkbox-custom")).click();
    driver.findElement(By.cssSelector(".justify-center:nth-child(1)")).click();

    WebElement signupButton = driver.findElement(By.id("signupBut"));
    Actions builder = new Actions(driver);
    builder.moveToElement(signupButton).perform();

    js.executeScript("window.scrollTo(0,0)");
  }
}
