package frontend.unit;

// Generated by Selenium IDE - Adapted for JUnit 5
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
import java.time.Duration;

public class UICollectionTest extends BaseUnitTest {
  private JavascriptExecutor js;

  @BeforeEach
  public void setUpTest() {
    super.setUp();
    js = (JavascriptExecutor) driver;

    helper.login("admin", "adminpass");
  }

  @Test
  public void collectioncrud() {
    // Test name: Collection CRUD - Create, Read, Update, Delete
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

    String randomSuffix = String.valueOf(System.currentTimeMillis());
    String colName = "Test Col " + randomSuffix;
    String updatedColName = "Updated Col " + randomSuffix;

    driver.get("https://localhost:8443/");
    driver.manage().window().setSize(new Dimension(1920, 1080));

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button.create-recipe-btn"))).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.id("recipeLabel"))).click();
    wait.until(ExpectedConditions.presenceOfElementLocated(By.id("recipeLabel"))).sendKeys("Temp Recipe for Collection");
    wait.until(ExpectedConditions.presenceOfElementLocated(By.id("recipeDesc"))).sendKeys("Temp desc");

    for (int i = 0; i < 3; i++) {
      wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".flex:nth-child(3) > .ti-caret-up-filled"))).click();
    }
    for (int i = 0; i < 3; i++) {
      wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".flex:nth-child(2) > .ti-caret-up-filled"))).click();
    }

    wait.until(ExpectedConditions.presenceOfElementLocated(By.name("difficulty"))).sendKeys("2");
    wait.until(ExpectedConditions.presenceOfElementLocated(By.name("category"))).sendKeys("Snack");

    js.executeScript("window.scrollTo(0,300)");

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement createBtn = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".publishBut button")));
    jsClick(createBtn);

    wait.until(ExpectedConditions.urlMatches(".*/recipes/\\d+"));
    String currentUrl = driver.getCurrentUrl();
    String recipeId = currentUrl.substring(currentUrl.lastIndexOf("/") + 1);

    // ========== CREATE COLLECTION ==========
    driver.get("https://localhost:8443/");
    driver.manage().window().setSize(new Dimension(1920, 1080));

    js.executeScript("window.scrollTo(0,24)");

    wait.until(ExpectedConditions.presenceOfElementLocated(By.className("recipe-card")));

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".recipe-card .ti-bookmark")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    WebElement btnElement = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".recipe-card .ti-bookmark")));
    jsClick(btnElement);

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.tagName("body")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }

    js.executeScript("window.scrollTo(0,0)");

    WebElement createNewBtn = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".visibleBackdrop button[style*='gradient-primary']")));
    jsClick(createNewBtn);

    WebElement collectionInput = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".visibleBackdrop input[type='text']")));
    collectionInput.click();
    collectionInput.sendKeys(colName);

    WebElement checkBtn = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".visibleBackdrop .ti-check")));
    jsClick(checkBtn);

    wait.until(ExpectedConditions.invisibilityOfElementLocated(By.className("visibleBackdrop")));

    // ========== ADD RECIPE TO COLLECTION ==========
    driver.get("https://localhost:8443/");
    driver.manage().window().setSize(new Dimension(1920, 1080));

    js.executeScript("window.scrollTo(0,246)");

    wait.until(ExpectedConditions.presenceOfElementLocated(By.className("recipe-card")));

    WebElement addBtn = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".recipe-card .ti-bookmark")));
    jsClick(addBtn);

    js.executeScript("window.scrollTo(0,0)");

    WebElement selectBtn = wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//div[contains(@class, 'visibleBackdrop')]//button[contains(., '" + colName + "')]")));
    jsClick(selectBtn);

    wait.until(ExpectedConditions.invisibilityOfElementLocated(By.className("visibleBackdrop")));

    // ========== EDIT COLLECTION ==========
    driver.get("https://localhost:8443/");
    driver.manage().window().setSize(new Dimension(1837, 944));

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".aspect-square"))).click();

    js.executeScript("window.scrollTo(0,200)");

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".tab:nth-child(3)"))).click();

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".flex:nth-child(2) > .flex > .flex > .w-8:nth-child(1) > .ti"))).click();
    
    WebElement titleInput = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".flex-1")));
    titleInput.clear();
    titleInput.sendKeys(updatedColName);

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".ti-check"))).click();

    wait.until(ExpectedConditions.invisibilityOfElementLocated(By.cssSelector("input.flex-1")));

    // ========== DELETE COLLECTION ==========
    driver.get("https://localhost:8443/");
    driver.manage().window().setSize(new Dimension(1837, 944));

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".glass:nth-child(1) > .flex > .btn"))).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".hover\\3Askew-x-12"))).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".\\!delete-collection-btn > .font-semibold"))).click();

    wait.until(ExpectedConditions.invisibilityOfElementLocated(By.xpath("//span[contains(text(), '" + updatedColName + "')]")));

    // ========== CLEANUP RECIPE ==========
    driver.get("https://localhost:8443/recipes/" + recipeId);
    wait.until(ExpectedConditions.presenceOfElementLocated(By.className("recipeCont")));

    WebElement deleteBtn = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".recipeOptions .ti-trash")));
    jsClick(deleteBtn);

    try {
      Thread.sleep(300);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement confirmBtn = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".px-8:nth-child(2)")));
    jsClick(confirmBtn);

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }
  }
}