package frontend.unit;

// Generated by Selenium IDE - Adapted for JUnit 5
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
import java.time.Duration;

public class UICollectionTest extends BaseUnitTest {
  private JavascriptExecutor js;

  private void jsClick(WebElement element) {
    js.executeScript("arguments[0].click();", element);
  }

  @BeforeEach
  public void setUpTest() {
    super.setUp();
    js = (JavascriptExecutor) driver;

    // Login with admin user
    driver.get("http://localhost:4200/login");
    driver.manage().window().setSize(new Dimension(1094, 944));
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("admin");
    js.executeScript("window.scrollTo(0,100)");
    driver.findElement(By.id("login-password")).sendKeys("adminpass");
    driver.findElement(By.id("loginBut")).click();

    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    wait.until(ExpectedConditions.urlToBe("http://localhost:4200/"));

    wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("body")));

    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }
  }

  @Test
  public void collectioncrud() {
    // Test name: Collection CRUD - Create, Read, Update, Delete
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

    // ========== CREATE COLLECTION ==========
    driver.get("http://localhost:4200/");
    driver.manage().window().setSize(new Dimension(1094, 944));

    js.executeScript("window.scrollTo(0,24)");

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".flex:nth-child(3) > .imageCont .btn:nth-child(2)")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    WebElement btnElement = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".flex:nth-child(3) > .imageCont .btn:nth-child(2)")));
    jsClick(btnElement);

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.tagName("body")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }

    js.executeScript("window.scrollTo(0,0)");

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement createNewBtn = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".w-full > .font-semibold")));
    jsClick(createNewBtn);

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".px-4"))).click();
    wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".px-4"))).sendKeys("Test Collection");

    WebElement checkBtn = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".ti-check")));
    jsClick(checkBtn);

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    // ========== ADD RECIPE TO COLLECTION ==========
    driver.get("http://localhost:4200/");
    driver.manage().window().setSize(new Dimension(1094, 944));

    js.executeScript("window.scrollTo(0,246)");

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement addBtn = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".flex:nth-child(3) > .imageCont .btn:nth-child(2)")));
    jsClick(addBtn);

    js.executeScript("window.scrollTo(0,0)");

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement selectBtn = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".w-full > .font-semibold")));
    jsClick(selectBtn);

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    // ========== EDIT COLLECTION ==========
    driver.get("http://localhost:4200/");
    driver.manage().window().setSize(new Dimension(1837, 944));

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".aspect-square"))).click();

    js.executeScript("window.scrollTo(0,200)");

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".tab:nth-child(3)"))).click();

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".flex:nth-child(2) > .flex > .flex > .w-8:nth-child(1) > .ti"))).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".flex-1"))).click();

    WebElement titleInput = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".flex-1")));
    titleInput.clear();
    titleInput.sendKeys("Updated Collection");

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".ti-check"))).click();

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    // ========== DELETE COLLECTION ==========
    driver.get("http://localhost:4200/");
    driver.manage().window().setSize(new Dimension(1837, 944));

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".glass:nth-child(1) > .flex > .btn"))).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".hover\\3Askew-x-12"))).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".\\!delete-collection-btn > .font-semibold"))).click();

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }
  }
}
