package frontend.unit;

// Generated by Selenium IDE - Adapted for JUnit 5
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.time.Duration;

public class UIMiscellaneousTest extends BaseUnitTest {
  private JavascriptExecutor js;

  @BeforeEach
  public void setUpTest() {
    super.setUp();
    js = (JavascriptExecutor) driver;
  }

  @Test
  public void changelanguage() {
    driver.get("https://localhost:8443/");
    driver.manage().window().setSize(new Dimension(1837, 944));

    helper.pause(1000);

    helper.jsClickAfterVisible(By.id("selectedLangText"));

    helper.pause(500);

    helper.jsClickAfterVisible(By.cssSelector("[id*='dropdownLangMenu'] .dropdown-item:nth-child(2)"));

    helper.pause(500);
  }

  @Test
  public void changetheme() {
    driver.get("https://localhost:8443/");
    driver.manage().window().setSize(new Dimension(1837, 944));

    helper.pause(1000);

    helper.jsClickAfterVisible(By.id("dropdownTrigger"));

    helper.pause(500);

    helper.jsClickAfterVisible(By.cssSelector("[class*='rose-dark'] .absolute, [class*='dark-mode'] .absolute"));

    helper.pause(500);
  }

  @Test
  public void searchsomething() {
    driver.get("https://localhost:8443/");
    driver.manage().window().setSize(new Dimension(1837, 944));

    helper.waitAndGetElement(By.cssSelector("body"));

    helper.pause(2000);

    driver.get("https://localhost:8443/explore");

    helper.pause(1000);

    helper.jsClickAfterVisible(By.cssSelector(".tab[class*='active'], .tabs .tab:not(.active)"));

    helper.pause(500);

    helper.waitAndSendKeys(By.cssSelector(".pl-14"), "a");
    helper.jsClickAfterVisible(By.cssSelector(".pl-14"));

    js.executeScript("arguments[0].dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter' }));",
      driver.findElement(By.cssSelector(".pl-14")));

    helper.pause(500);

    {
      helper.waitAndGetElement(By.cssSelector(".right-3"));
    }

    {
      helper.waitAndGetElement(By.tagName("body"));
    }
  }

  @Test
  public void filtersomething() {
    driver.get("https://localhost:8443/");
    driver.manage().window().setSize(new Dimension(1837, 944));

    helper.waitAndGetElement(By.cssSelector("body"));

    helper.pause(2000);

    driver.get("https://localhost:8443/explore");

    helper.pause(1000);

    helper.jsClickAfterVisible(By.cssSelector("input[type='checkbox'] + span.checkbox-custom"));

    helper.pause(500);

    helper.jsClickAfterVisible(By.cssSelector("button[class*='border-none']"));

    {
      helper.waitAndGetElement(By.cssSelector("button[class*='border-none']"));
    }

    {
      helper.waitAndGetElement(By.tagName("body"));
    }

    helper.pause(500);

    helper.jsClickAfterVisible(By.cssSelector(".w-full:not(.pl-14)"));

    helper.pause(500);

    {
      helper.waitAndGetElement(By.cssSelector("[class*='ti-list']"));
    }

    helper.jsClickAfterVisible(By.cssSelector("[class*='ti-list']"));

    {
      helper.waitAndGetElement(By.tagName("body"));
    }

    helper.pause(500);
  }
}
