package frontend.unit;

// Generated by Selenium IDE - Adapted for JUnit 5
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
import java.time.Duration;

public class UIMiscellaneousTest extends BaseUnitTest {
  private JavascriptExecutor js;

  private void jsClick(WebElement element) {
    js.executeScript("arguments[0].click();", element);
  }

  @BeforeEach
  public void setUpTest() {
    super.setUp();
    js = (JavascriptExecutor) driver;
  }

  @Test
  public void changelanguage() {
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

    driver.get("https://localhost:8443/");
    driver.manage().window().setSize(new Dimension(1837, 944));

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement langSelector = wait.until(ExpectedConditions.elementToBeClickable(By.id("selectedLangText")));
    jsClick(langSelector);

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement langOption = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("#dropdownLangMenu > .dropdown-item:nth-child(2)")));
    jsClick(langOption);

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }
  }

  @Test
  public void changetheme() {
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

    driver.get("https://localhost:8443/");
    driver.manage().window().setSize(new Dimension(1837, 944));

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement themeDropdown = wait.until(ExpectedConditions.elementToBeClickable(By.id("dropdownTrigger")));
    jsClick(themeDropdown);

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement themeOption = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".\\!rose-dark > .absolute")));
    jsClick(themeOption);

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }
  }

  @Test
  public void searchsomething() {
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(15));

    driver.get("https://localhost:8443/");
    driver.manage().window().setSize(new Dimension(1837, 944));

    wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("body")));

    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    driver.get("https://localhost:8443/explore");

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".tab:nth-child(3)"))).click();

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement searchInput = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".pl-14")));
    searchInput.click();
    searchInput.sendKeys("a");
    searchInput.sendKeys(Keys.ENTER);

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".right-3")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.tagName("body")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }

  @Test
  public void filtersomething() {
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(15));

    driver.get("https://localhost:8443/");
    driver.manage().window().setSize(new Dimension(1837, 944));

    wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("body")));

    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    driver.get("https://localhost:8443/explore");

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement filterCheckbox = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".space-y-2 > .flex:nth-child(2) > .checkbox-custom")));
    jsClick(filterCheckbox);

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement applyBtn = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".border-none")));
    jsClick(applyBtn);

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".border-none")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.tagName("body")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement dropdown = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".w-full:nth-child(4)")));
    jsClick(dropdown);

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".ti-list")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    WebElement listToggle = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".ti-list")));
    jsClick(listToggle);

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.tagName("body")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }
  }
}
