package frontend.unit;

// Generated by Selenium IDE - Adapted for JUnit 5
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
import java.time.Duration;

public class UIReviewTest extends BaseUnitTest {
  private JavascriptExecutor js;

  private void jsClick(WebElement element) {
    js.executeScript("arguments[0].click();", element);
  }

  @BeforeEach
  public void setUpTest() {
    super.setUp();
    js = (JavascriptExecutor) driver;

    // Login with admin user
    driver.get("http://localhost:4200/login");
    driver.manage().window().setSize(new Dimension(1094, 944));
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("admin");
    js.executeScript("window.scrollTo(0,100)");
    driver.findElement(By.id("login-password")).sendKeys("adminpass");
    driver.findElement(By.id("loginBut")).click();

    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    wait.until(ExpectedConditions.urlToBe("http://localhost:4200/"));

    wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("body")));

    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }
  }
  @Test
  public void reviewcrud() {
    // Test name: Review CRUD - Create and Delete
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

    // ========== CREATE REVIEW ==========
    driver.get("http://localhost:4200/");
    driver.manage().window().setSize(new Dimension(1094, 944));

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement recipeButton = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".flex:nth-child(1) .absolute:nth-child(2)")));
    js.executeScript("arguments[0].click();", recipeButton);

    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,0)");

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".tab:nth-child(3)"))).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".rounded-2xl"))).click();

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".transition-all:nth-child(4) > .ti"))).click();

    try {
      Thread.sleep(800);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement editor = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".min-h-\\[150px\\]")));

    js.executeScript("arguments[0].scrollIntoView({behavior: 'instant', block: 'center'});", editor);

    try {
      Thread.sleep(300);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    js.executeScript("arguments[0].focus();", editor);

    try {
      Thread.sleep(300);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    String reviewText = "Good, <b>Very Good</b>";

    js.executeScript("arguments[0].innerHTML = '<p>" + reviewText + "</p>';", editor);

    js.executeScript(
        "var event = new Event('input', { bubbles: true, cancelable: true });" +
        "arguments[0].dispatchEvent(event);",
        editor
    );

    js.executeScript(
        "var event = new Event('change', { bubbles: true, cancelable: true });" +
        "arguments[0].dispatchEvent(event);",
        editor
    );

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    String editorContent = (String) js.executeScript("return arguments[0].innerText || arguments[0].textContent;", editor);

    if (editorContent == null || editorContent.trim().isEmpty()) {
      editor.click();
      editor.sendKeys(reviewText);
      try {
        Thread.sleep(500);
      } catch (InterruptedException e) {
        Thread.currentThread().interrupt();
      }
    }

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement submitButton = wait.until(ExpectedConditions.presenceOfElementLocated(
        By.cssSelector("button.flex-1.px-6.py-3, button.py-3")));

    js.executeScript("arguments[0].scrollIntoView({behavior: 'smooth', block: 'center'});", submitButton);

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    js.executeScript("arguments[0].click();", submitButton);

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    js.executeScript("window.scrollTo(0,0)");

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    // ========== DELETE REVIEW ==========
    driver.get("http://localhost:4200/");
    driver.manage().window().setSize(new Dimension(1094, 944));

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement recipeButtonDelete = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".flex:nth-child(1) .absolute:nth-child(2)")));
    js.executeScript("arguments[0].click();", recipeButtonDelete);

    js.executeScript("window.scrollTo(0,0)");

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".tab:nth-child(3)"))).click();

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".tab:nth-child(3)")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.tagName("body")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }

    js.executeScript("window.scrollTo(0,0)");

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn > .ti"))).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".ti-check"))).click();

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }
  }
}
