package frontend.unit;

// Generated by Selenium IDE - Adapted for JUnit 5
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
import java.time.Duration;

public class UIRecipeTest extends BaseUnitTest {
  private JavascriptExecutor js;

  private void jsClick(WebElement element) {
    js.executeScript("arguments[0].click();", element);
  }

  @BeforeEach
  public void setUpTest() {
    super.setUp();
    js = (JavascriptExecutor) driver;

    // Login with admin user
    driver.get("http://localhost:4200/login");
    driver.manage().window().setSize(new Dimension(1094, 944));
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("admin");
    js.executeScript("window.scrollTo(0,100)");
    driver.findElement(By.id("login-password")).sendKeys("adminpass");
    driver.findElement(By.id("loginBut")).click();

    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    wait.until(ExpectedConditions.urlToBe("http://localhost:4200/"));

    wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("body")));

    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }
  }
  @Test
  public void recipecrud() {
    // Test name: Recipe CRUD - Create, Read, Update, Delete
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

    // ========== CREATE RECIPE ==========
    driver.get("http://localhost:4200/");
    driver.manage().window().setSize(new Dimension(1094, 944));

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".w-max > span"))).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.id("recipeLabel"))).click();
    wait.until(ExpectedConditions.presenceOfElementLocated(By.id("recipeLabel"))).sendKeys("Test Recipe");
    wait.until(ExpectedConditions.presenceOfElementLocated(By.id("recipeDesc"))).sendKeys("Test recipe description");

    for (int i = 0; i < 3; i++) {
      wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".flex:nth-child(3) > .ti-caret-up-filled"))).click();
    }
    for (int i = 0; i < 3; i++) {
      wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".flex:nth-child(2) > .ti-caret-up-filled"))).click();
    }

    wait.until(ExpectedConditions.presenceOfElementLocated(By.name("difficulty"))).sendKeys("2");
    wait.until(ExpectedConditions.presenceOfElementLocated(By.name("category"))).sendKeys("Snack");

    js.executeScript("window.scrollTo(0,300)");

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement createBtn = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".gap-3")));
    jsClick(createBtn);

    js.executeScript("window.scrollTo(0,0)");

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    // ========== EDIT RECIPE ==========
    driver.get("http://localhost:4200/");
    driver.manage().window().setSize(new Dimension(1094, 944));

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement recipeCard = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".flex:nth-child(1) .absolute:nth-child(2)")));
    jsClick(recipeCard);

    js.executeScript("window.scrollTo(0,0)");

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".tab:nth-child(2)")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    WebElement editBtn = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".rounded-xl:nth-child(1)")));
    jsClick(editBtn);

    wait.until(ExpectedConditions.elementToBeClickable(By.id("recipeLabel"))).click();

    WebElement labelInput = wait.until(ExpectedConditions.presenceOfElementLocated(By.id("recipeLabel")));
    labelInput.clear();
    labelInput.sendKeys("Updated Recipe");

    wait.until(ExpectedConditions.elementToBeClickable(By.id("recipeDesc"))).click();

    WebElement descInput = wait.until(ExpectedConditions.presenceOfElementLocated(By.id("recipeDesc")));
    descInput.clear();
    descInput.sendKeys("Updated description");

    js.executeScript("window.scrollTo(0,300)");

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement updateBtn = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".gap-3")));
    jsClick(updateBtn);

    js.executeScript("window.scrollTo(0,0)");

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    // ========== DELETE RECIPE ==========
    driver.get("http://localhost:4200/");
    driver.manage().window().setSize(new Dimension(1094, 944));

    js.executeScript("window.scrollTo(0,283)");

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement recipeCardDelete = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".flex:nth-child(1) .absolute:nth-child(2)")));
    jsClick(recipeCardDelete);

    js.executeScript("window.scrollTo(0,0)");

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement deleteBtn = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".ti-trash")));
    jsClick(deleteBtn);

    try {
      Thread.sleep(300);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement confirmBtn = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".px-8:nth-child(2)")));
    jsClick(confirmBtn);

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }
  }
}
