package frontend.unit;

// Generated by Selenium IDE - Adapted for JUnit 5
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
import java.time.Duration;

public class UIRecipeTest extends BaseUnitTest {
  private JavascriptExecutor js;

  @BeforeEach
  public void setUpTest() {
    super.setUp();
    js = (JavascriptExecutor) driver;

    helper.login("admin", "adminpass");
  }
  @Test
  public void recipecrud() {
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

    // ========== CREATE RECIPE ==========
    driver.get("https://localhost:8443/");
    driver.manage().window().setSize(new Dimension(1920, 1080));

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button.create-recipe-btn"))).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.id("recipeLabel"))).click();
    wait.until(ExpectedConditions.presenceOfElementLocated(By.id("recipeLabel"))).sendKeys("Test Recipe");
    wait.until(ExpectedConditions.presenceOfElementLocated(By.id("recipeDesc"))).sendKeys("Test recipe description");

    for (int i = 0; i < 3; i++) {
      wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".flex:nth-child(3) > .ti-caret-up-filled"))).click();
    }
    for (int i = 0; i < 3; i++) {
      wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".flex:nth-child(2) > .ti-caret-up-filled"))).click();
    }

    wait.until(ExpectedConditions.presenceOfElementLocated(By.name("difficulty"))).sendKeys("2");
    wait.until(ExpectedConditions.presenceOfElementLocated(By.name("category"))).sendKeys("Snack");

    js.executeScript("window.scrollTo(0,300)");

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement createBtn = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".publishBut button")));
    jsClick(createBtn);

    wait.until(ExpectedConditions.urlMatches(".*/recipes/\\d+"));
    String currentUrl = driver.getCurrentUrl();
    String recipeId = currentUrl.substring(currentUrl.lastIndexOf("/") + 1);

    // ========== EDIT RECIPE ==========
    driver.get("https://localhost:8443/recipes/" + recipeId);
    driver.manage().window().setSize(new Dimension(1920, 1080));

    wait.until(ExpectedConditions.presenceOfElementLocated(By.className("recipeCont")));

    js.executeScript("window.scrollTo(0,0)");

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".tab:nth-child(2)")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    WebElement editBtn = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".recipeEdit")));
    jsClick(editBtn);

    wait.until(ExpectedConditions.elementToBeClickable(By.id("recipeLabel"))).click();
    WebElement labelInput = wait.until(ExpectedConditions.presenceOfElementLocated(By.id("recipeLabel")));
    labelInput.clear();
    labelInput.sendKeys("Updated Recipe");

    wait.until(ExpectedConditions.elementToBeClickable(By.id("recipeDesc"))).click();
    WebElement descInput = wait.until(ExpectedConditions.presenceOfElementLocated(By.id("recipeDesc")));
    descInput.clear();
    descInput.sendKeys("Updated description");

    js.executeScript("window.scrollTo(0,300)");

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement updateBtn = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".publishBut button")));
    jsClick(updateBtn);

    wait.until(ExpectedConditions.urlToBe("https://localhost:8443/recipes/" + recipeId));

    // ========== DELETE RECIPE ==========
    driver.get("https://localhost:8443/recipes/" + recipeId);
    driver.manage().window().setSize(new Dimension(1920, 1080));

    wait.until(ExpectedConditions.presenceOfElementLocated(By.className("recipeCont")));

    js.executeScript("window.scrollTo(0,0)");

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement deleteBtn = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".ti-trash")));
    jsClick(deleteBtn);

    try {
      Thread.sleep(300);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement confirmBtn = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".px-8:nth-child(2)")));
    jsClick(confirmBtn);

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }
  }
}