package frontend.unit;

// Generated by Selenium IDE - Adapted for JUnit 5
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
import java.time.Duration;

public class UIReviewTest extends BaseUnitTest {
  private JavascriptExecutor js;

  @BeforeEach
  public void setUpTest() {
    super.setUp();
    js = (JavascriptExecutor) driver;

    // Login with admin user
    helper.login("admin", "adminpass");
  }
  @Test
  public void reviewcrud() {
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

    // ========== CREATE TEMP RECIPE ==========
    driver.get("https://localhost:8443/");
    driver.manage().window().setSize(new Dimension(1920, 1080));

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button.create-recipe-btn"))).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.id("recipeLabel"))).click();
    wait.until(ExpectedConditions.presenceOfElementLocated(By.id("recipeLabel"))).sendKeys("Temp Recipe For Review");
    wait.until(ExpectedConditions.presenceOfElementLocated(By.id("recipeDesc"))).sendKeys("Temporary recipe description");

    for (int i = 0; i < 3; i++) {
      wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".flex:nth-child(3) > .ti-caret-up-filled"))).click();
    }
    for (int i = 0; i < 3; i++) {
      wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".flex:nth-child(2) > .ti-caret-up-filled"))).click();
    }

    wait.until(ExpectedConditions.presenceOfElementLocated(By.name("difficulty"))).sendKeys("2");
    wait.until(ExpectedConditions.presenceOfElementLocated(By.name("category"))).sendKeys("Snack");

    js.executeScript("window.scrollTo(0,300)");

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement createBtn = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".publishBut button")));
    jsClick(createBtn);

    wait.until(ExpectedConditions.urlMatches(".*/recipes/\\d+"));
    String currentUrl = driver.getCurrentUrl();
    String recipeId = currentUrl.substring(currentUrl.lastIndexOf("/") + 1);

    // ========== CREATE REVIEW ==========
    driver.get("https://localhost:8443/recipes/" + recipeId);
    driver.manage().window().setSize(new Dimension(1920, 1080));

    wait.until(ExpectedConditions.presenceOfElementLocated(By.className("recipeCont")));

    js.executeScript("window.scrollTo(0,0)");

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".tab:nth-child(3)"))).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".rounded-2xl"))).click();

    helper.waitForClickable(By.cssSelector(".rating-star-btn:nth-child(4)")).click();

    WebElement editor = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".min-h-\\[150px\\]")));
    js.executeScript("arguments[0].scrollIntoView({behavior: 'instant', block: 'center'});", editor);
    js.executeScript("arguments[0].focus();", editor);

    String reviewText = "Good, <b>Very Good</b>";
    js.executeScript("arguments[0].innerHTML = '<p>" + reviewText + "</p>';", editor);

    js.executeScript(
        "var event = new Event('input', { bubbles: true, cancelable: true });" +
        "arguments[0].dispatchEvent(event);",
        editor
    );
    js.executeScript(
        "var event = new Event('change', { bubbles: true, cancelable: true });" +
        "arguments[0].dispatchEvent(event);",
        editor
    );

    String editorContent = (String) js.executeScript("return arguments[0].innerText || arguments[0].textContent;", editor);
    if (editorContent == null || editorContent.trim().isEmpty()) {
      editor.click();
      editor.sendKeys(reviewText);
    }

    WebElement submitButton = wait.until(ExpectedConditions.presenceOfElementLocated(
        By.cssSelector("button.flex-1.px-6.py-3, button.py-3")));

    js.executeScript("arguments[0].scrollIntoView({behavior: 'smooth', block: 'center'});", submitButton);
    js.executeScript("arguments[0].click();", submitButton);

    wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".yourReview")));

    js.executeScript("window.scrollTo(0,0)");

    // ========== DELETE REVIEW ==========
    driver.get("https://localhost:8443/recipes/" + recipeId);
    driver.manage().window().setSize(new Dimension(1920, 1080));

    wait.until(ExpectedConditions.presenceOfElementLocated(By.className("recipeCont")));

    js.executeScript("window.scrollTo(0,0)");

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".tab:nth-child(3)"))).click();

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".tab:nth-child(3)")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.tagName("body")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }

    js.executeScript("window.scrollTo(0,0)");

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".yourReview .deleteBut"))).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".yourReview .confirmDelete"))).click();

    wait.until(ExpectedConditions.invisibilityOfElementLocated(By.cssSelector(".yourReview")));

    // ========== CLEANUP RECIPE ==========
    driver.get("https://localhost:8443/recipes/" + recipeId);
    wait.until(ExpectedConditions.presenceOfElementLocated(By.className("recipeCont")));

    WebElement deleteBtn = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".ti-trash")));
    jsClick(deleteBtn);

    try {
      Thread.sleep(300);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    WebElement confirmBtn = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".px-8:nth-child(2)")));
    jsClick(confirmBtn);

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }
  }
}