package frontend.unit;

// Generated by Selenium IDE - Adapted for JUnit 5
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
import java.time.Duration;

public class UIUserTest extends BaseUnitTest {
  private JavascriptExecutor js;

  @BeforeEach
  public void setUpTest() {
    super.setUp();
    js = (JavascriptExecutor) driver;

    // Login with admin user
    driver.get("https://localhost:8443/login");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("admin");
    js.executeScript("window.scrollTo(0,100)");
    driver.findElement(By.id("login-password")).sendKeys("adminpass");
    driver.findElement(By.id("loginBut")).click();

    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    wait.until(ExpectedConditions.urlToBe("https://localhost:8443/"));

    wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("body")));

    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }
  }
  @Test
  public void usercrud() {
    // Test name: User CRUD - Update and Delete Profile
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

    // ========== EDIT PROFILE ==========
    driver.get("https://localhost:8443/");
    driver.manage().window().setSize(new Dimension(1923, 944));

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".aspect-square"))).click();

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".top-7"))).click();

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".top-7")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".bioInput"))).click();
    wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".bioInput"))).sendKeys("Updated bio");

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".flex:nth-child(1) > .switch > .slider"))).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".displayNameInput"))).click();
    wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".displayNameInput"))).sendKeys("Updated Name");

    WebElement emailInput = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".emailInput")));
    emailInput.click();
    emailInput.clear();
    emailInput.sendKeys("updated@example.com");

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".transition-all:nth-child(2)"))).click();

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    // ========== DELETE PROFILE ==========
    driver.get("https://localhost:8443/");
    driver.manage().window().setSize(new Dimension(2047, 944));

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".aspect-square"))).click();

    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }



    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".top-7"))).click();

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".top-7")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".py-3 > span"))).click();

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.id("deleteHoldBtnText")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".py-3 > span")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    js.executeScript("window.scrollTo(0,82)");
    js.executeScript("window.scrollTo(0,400)");

    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }
  }
}
